var files_dup =
[
    [ "allocate_buffer.hh", "allocate__buffer_8hh_source.html", null ],
    [ "allocator_malloc.hh", "allocator__malloc_8hh_source.html", null ],
    [ "base64.h", "base64_8h.html", "base64_8h" ],
    [ "bcd.h", "bcd_8h_source.html", null ],
    [ "cli.h", "cli_8h.html", "cli_8h" ],
    [ "cli_out.h", "cli__out_8h.html", "cli__out_8h" ],
    [ "cli_types.h", "cli__types_8h.html", "cli__types_8h" ],
    [ "comp_settings.hh", "comp__settings_8hh.html", "comp__settings_8hh" ],
    [ "config.h", "config_8h.html", "config_8h" ],
    [ "content.hh", "content_8hh_source.html", null ],
    [ "cstring_utils.h", "cstring__utils_8h_source.html", null ],
    [ "cstring_utils.hh", "cstring__utils_8hh_source.html", null ],
    [ "dbg.h", "dbg_8h_source.html", null ],
    [ "ethernet_setup.hh", "ethernet__setup_8hh.html", "ethernet__setup_8hh" ],
    [ "ftoa.h", "ftoa_8h_source.html", null ],
    [ "generated_opts.hh", "generated__opts_8hh_source.html", null ],
    [ "host_mqtt.h", "host__mqtt_8h_source.html", null ],
    [ "http_client.h", "http__client_8h.html", "http__client_8h" ],
    [ "http_server_esp32.h", "http__server__esp32_8h.html", "http__server__esp32_8h" ],
    [ "http_server_setup.h", "http__server__setup_8h.html", "http__server__setup_8h" ],
    [ "inout.h", "inout_8h_source.html", null ],
    [ "int_macros.h", "int__macros_8h.html", "int__macros_8h" ],
    [ "int_types.h", "int__types_8h_source.html", null ],
    [ "ipnet.h", "ipnet_8h.html", "ipnet_8h" ],
    [ "itoa.h", "itoa_8h_source.html", null ],
    [ "jsmn.h", "jsmn_8h_source.html", null ],
    [ "jsmn_iterate.hh", "jsmn__iterate_8hh.html", [
      [ "JsmnBase", "classJsmnBase.html", "classJsmnBase" ],
      [ "Iterator", "structJsmnBase_1_1Iterator.html", "structJsmnBase_1_1Iterator" ],
      [ "Jsmn", "classJsmn.html", "classJsmn" ]
    ] ],
    [ "kvs_wrapper.h", "kvs__wrapper_8h_source.html", null ],
    [ "log.h", "log_8h_source.html", null ],
    [ "main_queue.hh", "main__queue_8hh_source.html", null ],
    [ "mqtt.hh", "mqtt_8hh.html", "mqtt_8hh" ],
    [ "mutex.h", "mutex_8h_source.html", null ],
    [ "cli/include/cli/mutex.hh", "cli_2include_2cli_2mutex_8hh_source.html", null ],
    [ "utils_misc/include/utils_misc/mutex.hh", "utils__misc_2include_2utils__misc_2mutex_8hh_source.html", null ],
    [ "new_malloc.hh", "new__malloc_8hh_source.html", null ],
    [ "ntp_client_setup.hh", "ntp__client__setup_8hh.html", "ntp__client__setup_8hh" ],
    [ "options.hh", "options_8hh.html", "options_8hh" ],
    [ "ota.h", "ota_8h_source.html", null ],
    [ "periodic.h", "periodic_8h.html", "periodic_8h" ],
    [ "run_time.h", "run__time_8h.html", "run__time_8h" ],
    [ "settings.hh", "settings_8hh.html", "settings_8hh" ],
    [ "settings_template.hh", "settings__template_8hh_source.html", null ],
    [ "so_out.h", "so__out_8h.html", "so__out_8h" ],
    [ "so_target_bits.h", "so__target__bits_8h.html", "so__target__bits_8h" ],
    [ "so_target_desc.hh", "so__target__desc_8hh.html", [
      [ "UoutRawWriter", "classUoutRawWriter.html", "classUoutRawWriter" ],
      [ "mod", "structUoutRawWriter_1_1mod.html", "structUoutRawWriter_1_1mod" ],
      [ "UoutWriter", "classUoutWriter.html", "classUoutWriter" ],
      [ "UoutWriterConsole", "classUoutWriterConsole.html", "classUoutWriterConsole" ],
      [ "UoutWriterBuilder", "classUoutWriterBuilder.html", "classUoutWriterBuilder" ],
      [ "UoutWriterFunction", "classUoutWriterFunction.html", "classUoutWriterFunction" ],
      [ "UoutWriterFile", "classUoutWriterFile.html", "classUoutWriterFile" ]
    ] ],
    [ "status_json.hh", "status__json_8hh.html", [
      [ "UoutBuilderJson", "classUoutBuilderJson.html", "classUoutBuilderJson" ]
    ] ],
    [ "stm32.h", "stm32_8h.html", "stm32_8h" ],
    [ "stm32_bl.h", "stm32__bl_8h.html", "stm32__bl_8h" ],
    [ "stm32_ota.h", "stm32__ota_8h.html", "stm32__ota_8h" ],
    [ "stof.h", "stof_8h_source.html", null ],
    [ "storage.h", "storage_8h_source.html", null ],
    [ "string_malloc.hh", "string__malloc_8hh_source.html", null ],
    [ "sun.h", "sun_8h.html", "sun_8h" ],
    [ "tcp_cli_server.h", "tcp__cli__server_8h.html", "tcp__cli__server_8h" ],
    [ "tcp_cli_server_setup.hh", "tcp__cli__server__setup_8hh.html", "tcp__cli__server__setup_8hh" ],
    [ "time_out_secs.hh", "time__out__secs_8hh_source.html", null ],
    [ "txtio_mutex.hh", "txtio__mutex_8hh_source.html", null ],
    [ "txtio_setup.hh", "txtio__setup_8hh_source.html", null ],
    [ "uo_callbacks.h", "uo__callbacks_8h.html", "uo__callbacks_8h" ],
    [ "uo_config.h", "uo__config_8h_source.html", null ],
    [ "uo_types.h", "uo__types_8h.html", [
      [ "so_arg_pch_t", "structso__arg__pch__t.html", "structso__arg__pch__t" ]
    ] ],
    [ "ut_constants.hh", "ut__constants_8hh_source.html", null ],
    [ "ut_sleep.h", "ut__sleep_8h_source.html", null ],
    [ "weather.hh", "weather_8hh_source.html", null ],
    [ "weather_data.hh", "weather__data_8hh_source.html", null ],
    [ "weather_irrigation.hh", "weather__irrigation_8hh_source.html", null ],
    [ "weather_provider.hh", "weather__provider_8hh_source.html", null ],
    [ "weather_provider_owm.hh", "weather__provider__owm_8hh_source.html", null ],
    [ "weather_provider_random.hh", "weather__provider__random_8hh_source.html", null ],
    [ "wifi_ap_setup.h", "wifi__ap__setup_8h.html", "wifi__ap__setup_8h" ],
    [ "wifi_station_setup.hh", "wifi__station__setup_8hh.html", "wifi__station__setup_8hh" ]
];